ExRam/ExRam.Gremlinq

src/ExRam.Gremlinq.Providers.JanusGraph/GremlinQueryEnvironmentExtensions.cs, src/ExRam.Gremlinq.Providers.Neptune.AspNet/GremlinqSetupExtensions.cs, src/ExRam.Gremlinq.Providers.Neptune/GremlinQueryEnvironmentExtensions.cs, src/ExRam.Gremlinq.Providers.Neptune/INeptuneConfigurationBuilder.cs, src/ExRam.Gremlinq.Providers.Neptune/INeptuneConfigurationBuilderWithUri.cs, test/ExRam.Gremlinq.Providers.Neptune.Tests/NeptuneQuerySerializationTest.cs, test/ExRam.Gremlinq.PublicApi.Tests/PublicApiTests.Neptune.verified.cs
To get the previous behaviour, first call At(Uri) on the builder, then, if needed, configure the rest by calling ConfigureWebSocket(...).
=> Breaking: UseNeptune takes a transformation from INeptuneConfigurationBuilder

src/ExRam.Gremlinq.Core/Queries/GremlinQuery.explicit.cs, src/ExRam.Gremlinq.Core/Queries/QuerySemantics.cs, src/ExRam.Gremlinq.Core/Queries/Steps/CyclicPathStep.cs, src/ExRam.Gremlinq.Core/Queries/Steps/ProjectEdgeStep.cs, src/ExRam.Gremlinq.Core/Queries/Steps/ProjectVertexStep.cs, src/ExRam.Gremlinq.Core/Queries/Steps/SimplePathStep.cs, src/ExRam.Gremlinq.Core/Serialization/GremlinQueryFragmentSerializer.cs, test/ExRam.Gremlinq.Core.Tests/GremlinQueryFragmentSerializerTest.AllSteps.verified.txt, test/ExRam.Gremlinq.Core.Tests/TypeSystemTest.All_Steps_can_be_created.verified.txt, test/ExRam.Gremlinq.PublicApi.Tests/PublicApiTests.Core.verified.cs
Only add ProjectEdgeSteps and ProjectVertexSteps to a Traversal, let serialization do the rest. Don't add the IdentityStep in ToTraversal.
=> ProjectVertexStep and ProjectEdgeStep

src/ExRam.Gremlinq.Providers.WebSocket/Extensions/ConfigurableGremlinQuerySourceExtensions.cs, src/ExRam.Gremlinq.Providers.WebSocket/Extensions/WebSocketConfiguratorExtensions.cs, src/ExRam.Gremlinq.Providers.WebSocket/IWebSocketConfigurator.cs, test/ExRam.Gremlinq.PublicApi.Tests/PublicApiTests.WebSocket.verified.cs
Its functionality can be easily restored with the help of ConfigureGremlinClientFactory, as the new ConfigureGremlinClient-extension in WebSocketConfiguratorExtensions.cs shows.
=> Remove IWebSocketConfigurator.ConfigureGremlinClient.

src/ExRam.Gremlinq.Providers.WebSocket/Extensions/ConfigurableGremlinQuerySourceExtensions.cs, src/ExRam.Gremlinq.Providers.WebSocket/Extensions/WebSocketConfiguratorExtensions.cs, src/ExRam.Gremlinq.Providers.WebSocket/IWebSocketConfigurator.cs, test/ExRam.Gremlinq.PublicApi.Tests/PublicApiTests.WebSocket.verified.cs
Its functionality can be easily restored with the help of ConfigureGremlinClientFactory, as the new ConfigureMessageSerializer-extension in WebSocketConfiguratorExtensions.cs shows.
=> Remove IWebSocketConfigurator.ConfigureMessageSerializer.

src/ExRam.Gremlinq.Providers.WebSocket/Extensions/ConfigurableGremlinQuerySourceExtensions.cs, src/ExRam.Gremlinq.Providers.WebSocket/Extensions/WebSocketConfiguratorExtensions.cs, src/ExRam.Gremlinq.Providers.WebSocket/IWebSocketConfigurator.cs, test/ExRam.Gremlinq.PublicApi.Tests/PublicApiTests.WebSocket.verified.cs
This allows the removal of IWebSocketConfigurator.AuthenticateBy and IWebSocketConfigurator.At, which are easily recreated by ConfigureGremlinServer as the new extensions show.
=> Introduce IWebSocketConfigurator.ConfigureGremlinServer.

src/ExRam.Gremlinq.Core/Queries/GremlinQuery.cs, test/ExRam.Gremlinq.Core.Tests/GremlinQueryTest.Debug.verified.txt
This reverts an earlier change, but it's more consistent this way.
=> Always output a complex structure in Debug, even when there are no bindings

src/ExRam.Gremlinq.Core/Queries/GremlinQuery.explicit.cs, src/ExRam.Gremlinq.Core/Queries/Interfaces/IStartGremlinQuery.cs, test/ExRam.Gremlinq.PublicApi.Tests/PublicApiTests.Core.verified.cs
It'll save an array allocation in most cases.
=> Add an overload for V that takes a single id.

src/ExRam.Gremlinq.Core/Queries/StepLabel.cs, test/ExRam.Gremlinq.Core.Tests/QueryExecutionTest.cs, test/ExRam.Gremlinq.PublicApi.Tests/PublicApiTests.Core.verified.cs
First, the list of operators is not exhaustive, seconds, it's advised to use the Value property which lowers equality on TElement. That's enough for expressions.
=> Remove mixed equality and inequality operators on StepLabel.

src/ExRam.Gremlinq.Core/Extensions/AddStepHandlerExtensions.cs, src/ExRam.Gremlinq.Core/Extensions/ObjectExtensions.cs, src/ExRam.Gremlinq.Core/Extensions/TraversalExtensions.cs, src/ExRam.Gremlinq.Core/Queries/ContinuationBuilder/ContinuationBuilder.cs, src/ExRam.Gremlinq.Core/Queries/GremlinQuery.ChooseBuilder.cs, src/ExRam.Gremlinq.Core/Queries/GremlinQuery.GroupBuilder.cs, src/ExRam.Gremlinq.Core/Queries/GremlinQuery.OrderBuilder.cs, src/ExRam.Gremlinq.Core/Queries/GremlinQuery.ProjectBuilder.cs, src/ExRam.Gremlinq.Core/Queries/GremlinQuery.cs, src/ExRam.Gremlinq.Core/Queries/GremlinQuery.explicit.cs, src/ExRam.Gremlinq.Core/Queries/GremlinQueryBase.cs, src/ExRam.Gremlinq.Core/Queries/Interfaces/Group/IGroupBuilder.cs, src/ExRam.Gremlinq.Core/Queries/Interfaces/Project/IProjectBuilder.cs, src/ExRam.Gremlinq.Core/Queries/T4/ProjectBuilder.cs, src/ExRam.Gremlinq.Core/Queries/T4/ProjectBuilder.tt, test/ExRam.Gremlinq.PublicApi.Tests/PublicApiTests.Core.verified.cs
It'll allow us to gather information from continued queries (such as side effect labels) at a central place in the code.
=> Introduce the internal concept of a ContinuationBuilder

src/ExRam.Gremlinq.Core.AspNet/Extensions/ServiceCollectionExtensions.cs, src/ExRam.Gremlinq.Core/Extensions/GremlinQueryExecutorExtensions.cs, src/ExRam.Gremlinq.Core/Options/GremlinqOption.cs, src/ExRam.Gremlinq.Core/Options/QueryLogFormatting.cs, test/ExRam.Gremlinq.PublicApi.Tests/PublicApiTests.Core.verified.cs, version.json
=> In a move away from Newtonsoft.Json, we introduce our own QueryLogFormatting enum.

src/ExRam.Gremlinq.Core/Cache/GremlinQueryEnvironmentCache.cs, src/ExRam.Gremlinq.Core/Environment/GremlinQueryEnvironment.cs, src/ExRam.Gremlinq.Core/Environment/IGremlinQueryEnvironment.cs, src/ExRam.Gremlinq.Core/ExpressionParsing/ExpressionFragment.cs, src/ExRam.Gremlinq.Core/Extensions/ExpressionExtensions.cs, src/ExRam.Gremlinq.Core/Extensions/GremlinQueryEnvironmentExtensions.cs, src/ExRam.Gremlinq.Core/Models/GraphModel.cs, src/ExRam.Gremlinq.Core/Models/IGraphModel.cs, src/ExRam.Gremlinq.Core/Queries/GremlinQuery.Helpers.cs, src/ExRam.Gremlinq.Core/Queries/GremlinQuery.cs, src/ExRam.Gremlinq.Core/Serialization/Serializer.cs, src/ExRam.Gremlinq.Providers.CosmosDb/Extensions/ConfigurableGremlinQuerySourceExtensions.cs, src/ExRam.Gremlinq.Providers.JanusGraph/Extensions/ConfigurableGremlinQuerySourceExtensions.cs, src/ExRam.Gremlinq.Providers.Neptune/Extensions/ConfigurableGremlinQuerySourceExtensions.cs, src/ExRam.Gremlinq.Support.NewtonsoftJson/Converters/BulkSetConverterFactory.cs, src/ExRam.Gremlinq.Support.NewtonsoftJson/Converters/EnumerableConverterFactory.cs, src/ExRam.Gremlinq.Support.NewtonsoftJson/Converters/LabelLookupConverterFactory.cs, src/ExRam.Gremlinq.Support.NewtonsoftJson/Converters/NativeTypeConverterFactory.cs, src/ExRam.Gremlinq.Support.NewtonsoftJson/Converters/SingleItemArrayFallbackConverterFactory.cs, src/ExRam.Gremlinq.Support.NewtonsoftJson/Converters/TimeSpanConverterFactory.cs, src/ExRam.Gremlinq.Support.NewtonsoftJson/Converters/VertexPropertyExtractConverterFactory.cs, src/ExRam.Gremlinq.Support.NewtonsoftJson/Extensions/GremlinQueryEnvironmentExtensions.cs, test/ExRam.Gremlinq.PublicApi.Tests/PublicApiTests.Core.verified.cs
The notion of native types is a property of the provider and not so much of the GraphModel. So it moves from GraphModel to IGremlinQueryEnvironment. In StoreByteArraysAsBase64String, do not remove byte[] from native types. The previous removal was always overriden by a new model and thus ineffective.
=> Rework notion of native types

src/ExRam.Gremlinq.Core/Execution/GremlinQueryExecutor.cs, src/ExRam.Gremlinq.Core/Execution/IGremlinQueryExecutor.cs, src/ExRam.Gremlinq.Core/Extensions/GremlinQueryExecutorExtensions.cs, src/ExRam.Gremlinq.Core/Queries/GremlinQuery.explicit.cs, src/ExRam.Gremlinq.Providers.Core/WebSocketProviderConfigurator.cs, test/ExRam.Gremlinq.Core.Tests/QueryExecutionTest.cs, test/ExRam.Gremlinq.PublicApi.Tests/PublicApiTests.Core.verified.cs, test/ExRam.Gremlinq.Support.NewtonsoftJson.Tests/Extensions/GremlinQuerySourceExtensions.cs, test/ExRam.Gremlinq.Support.NewtonsoftJson.Tests/IntegrationTestsBase.cs
...so that the serialization pipeline is really IGremlinQueryBase->RequestMessage, which opens up more opportunities to override behaviour.
=> IExecutor takes an IGremlinQueryBase

src/ExRam.Gremlinq.Core/Execution/GremlinQueryExecutor.cs, src/ExRam.Gremlinq.Core/Execution/IGremlinQueryExecutor.cs, src/ExRam.Gremlinq.Core/Queries/GremlinQuery.explicit.cs, src/ExRam.Gremlinq.Providers.Core/WebSocketProviderConfigurator.cs, test/ExRam.Gremlinq.Core.Tests/Extensions/GremlinQueryExecutorExtensions.cs, test/ExRam.Gremlinq.PublicApi.Tests/PublicApiTests.Core.verified.cs, test/ExRam.Gremlinq.Support.NewtonsoftJson.Tests/Extensions/GremlinQueryExecutorExtensions.cs
=> IGremlinQueryExecutor.Execute does not need the environment.

src/ExRam.Gremlinq.Core/Execution/GremlinQueryExecutionContext.cs, src/ExRam.Gremlinq.Core/Execution/GremlinQueryExecutor.cs, src/ExRam.Gremlinq.Core/Execution/IGremlinQueryExecutor.cs, src/ExRam.Gremlinq.Core/Queries/GremlinQuery.explicit.cs, src/ExRam.Gremlinq.Core/Serialization/Serializer.cs, src/ExRam.Gremlinq.Providers.Core/WebSocketProviderConfigurator.cs, test/ExRam.Gremlinq.Core.Tests/Extensions/GremlinQueryExecutorExtensions.cs, test/ExRam.Gremlinq.PublicApi.Tests/PublicApiTests.Core.verified.cs, test/ExRam.Gremlinq.Support.NewtonsoftJson.Tests/Extensions/GremlinQueryExecutorExtensions.cs
It'll carry the query and an Id. Rework the serializer to produce RequestMessage.Builders. Add a convenience serializer from builder to message for the tests.
=> Introduce a notion of ExecutionContext for GremlinQueries.

src/Core/Environment/GremlinQueryEnvironment.cs, test/Support.NewtonsoftJson.Tests/TansformerTest.cs
Working without a model is useless and a pitfall for incorrect code.
=> The graph-model on the default environment should be invalid. 

src/Support.NewtonsoftJson/Converters/VertexOrEdgeConverterFactory.cs, test/Providers.CosmosDb.Tests/DeserializationTests.AddV_without_model.verified.txt, test/Providers.GremlinServer.Tests/DeserializationTests.AddV_without_model.verified.txt, test/Support.NewtonsoftJson.Tests/GraphsonSupportTest.Language_strongly_typed_without_model.verified.txt
That means no magic for empty models any more.
=> VertexOrEdgeConverterFactory must only work on types it know from the model. 

test/AssemblyInfo.cs
...since two test containers running at the same time is often too much for the Github actions runner.
=> Disable collection parallelization

src/Core/Serialization/Serializer.cs, src/Providers.Core/Extensions/RequestMessageBuilderExtensions.cs, src/Providers.Core/Extensions/RequestMessageExtensions.cs, src/Providers.Core/WebSocketProviderConfigurator.cs
If a message must be changed, use the Rebuild extension.
=> Don't deal with RequestMessage.Builder in the serializers.

src/Core/Queries/ContinuationBuilder/ContinuationBuilderExtensions.cs, src/Core/Queries/GremlinQuery.cs, src/Core/Serialization/Serializer.cs
Appending an otherwise empty traversal during serialization is too late as no information on whether we're on the top-level query is available. For whenever the steps on an IGremlinQuerySource are empty (but the source-steps aren't), we get a wrong call on Identity() on the source.
=> Push IdentityStep magic back into continuations

.github/workflows/announce.yml
=> The social media preview of the release page is utter boring.

meta/Directory.Build.props, src/Core/Queries/GremlinQuery.generated.cs, src/Core/Queries/GremlinQuery.tt, src/Core/Queries/Interfaces/IGremlinQuery.cs, test/PublicApi.Tests/PublicApiTests.Core.DotNet6_0.verified.cs, test/PublicApi.Tests/PublicApiTests.Core.DotNet7_0.verified.cs, test/PublicApi.Tests/PublicApiTests.Core.DotNet8_0.verified.cs
Be liberal in what you accept, so we lower the argument type of the step label passed into Aggregate/AggregateLocal. This is technically breaking, albeit not source breaking, so the bump in the minor version will do.
=> Lower argument types of StepLabels passed into Aggregate/AggregateLocal

src/Directory.Build.props
They are not usable on anything < .NET 8. They would be usable with an explicit reference to the System.Collections.Immutable nuget, but that's something I am not willing to do just for syntactic sugar.
=> Supress suggestions to use collection expressions.
